name: Ping Website Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (in UTC)
  workflow_dispatch:        # Optional: lets you run it manually

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping your website
        run: curl -s https://pavankumarportfolio.onrender.com/
